package com.example.serverside.service;

import java.util.List;

import com.example.serverside.model.PujaUser;

public interface UserService {
											
	//autogenerated
	PujaUser saveUser(PujaUser user);		

	PujaUser findByUsername(String username);

	List<PujaUser> findAllUsers();

	PujaUser updateUser(PujaUser user);

	Object getUser(Long id);

}
